#!/bin/bash
# GitHub Push Helper - AbyssIntuition Project
# Run these commands to push to GitHub

echo "🚀 AbyssIntuition - GitHub Push Helper"
echo ""
echo "Step 1: Create repository on GitHub"
echo "  → Visit: https://github.com/new"
echo "  → Name it: AbyssIntuition"
echo "  → Do NOT initialize with README/gitignore/license"
echo "  → Click: Create repository"
echo ""
echo "Step 2: Run this command to push:"
echo ""
echo "    git push -u origin main"
echo ""
echo "Step 3: Enter credentials when prompted"
echo "  Username: bhardwaj-ankit"
echo "  Password: Your Personal Access Token"
echo ""
echo "Step 4: Verify at:"
echo "  https://github.com/bhardwaj-ankit/AbyssIntuition"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Current status:"
echo "  Repository: /Users/ankitbhardwaj/Documents/AbyssIntuition"
echo "  Remote: https://github.com/bhardwaj-ankit/AbyssIntuition.git"
echo "  Commits ready: $(git rev-list --count HEAD)"
echo "  Branch: $(git branch --show-current)"
echo "  Status: $(git status --short | wc -l) changes (should be 0)"
echo ""
echo "Ready to push? Run: git push -u origin main"
